spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exercise
    username: root
    password: tjrwn12
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
